// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE8xfeTnHUWVUehCF7iTLPMww18I2Ujl0',
    appId: '1:196853117189:web:67921ca5d756602922c76c',
    messagingSenderId: '196853117189',
    projectId: 'character-app-5cf88',
    authDomain: 'character-app-5cf88.firebaseapp.com',
    storageBucket: 'character-app-5cf88.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRzOZP3Sy0CAQf-qmSLqJoPp7ghU3p6Mk',
    appId: '1:196853117189:android:0fa98f54e6611b3422c76c',
    messagingSenderId: '196853117189',
    projectId: 'character-app-5cf88',
    storageBucket: 'character-app-5cf88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG2ZYlEwdO72dbM7FlzxjKGU3aJxXh8c4',
    appId: '1:196853117189:ios:81fd38a9e6f17e0522c76c',
    messagingSenderId: '196853117189',
    projectId: 'character-app-5cf88',
    storageBucket: 'character-app-5cf88.firebasestorage.app',
    iosBundleId: 'com.example.flutterCharacters',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG2ZYlEwdO72dbM7FlzxjKGU3aJxXh8c4',
    appId: '1:196853117189:ios:81fd38a9e6f17e0522c76c',
    messagingSenderId: '196853117189',
    projectId: 'character-app-5cf88',
    storageBucket: 'character-app-5cf88.firebasestorage.app',
    iosBundleId: 'com.example.flutterCharacters',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE8xfeTnHUWVUehCF7iTLPMww18I2Ujl0',
    appId: '1:196853117189:web:4bf66263e821778a22c76c',
    messagingSenderId: '196853117189',
    projectId: 'character-app-5cf88',
    authDomain: 'character-app-5cf88.firebaseapp.com',
    storageBucket: 'character-app-5cf88.firebasestorage.app',
  );
}